apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deploy
  labels:
    app: hello-kubernetes
spec:
  replicas: 4
  selector:
    matchLabels:
      app: hello-kubernetes
  template:
    metadata:
      labels:
        app: hello-kubernetes
    spec:
      terminationGracePeriodSeconds: 1
      containers:
      - name: app
        image: tinazhouhui/hello-kubernetes
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
