apiVersion: v1
kind: Service
metadata:
  name: srv-nodeport
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 5000
    nodePort: 30000
    protocol: TCP
  selector:
    app: hello-kubernetes